version: "3.8"

services:
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data_container:/data/db
    restart: unless-stopped

volumes:
  mongodb_data_container:
